//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IService", Namespace = "http://tempuri.org/")]
public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback GetTableOperationCompleted;

    private System.Threading.SendOrPostCallback InsertTableOperationCompleted;

    private System.Threading.SendOrPostCallback EditTableOperationCompleted;

    private System.Threading.SendOrPostCallback GetDetailTableOperationCompleted;

    private System.Threading.SendOrPostCallback GetDetailFieldTableOperationCompleted;

    private System.Threading.SendOrPostCallback InsertDetailTableOperationCompleted;

    private System.Threading.SendOrPostCallback EditDetailTableOperationCompleted;

    /// <remarks/>
    public Service(string pUrl)
    {
        //this.Url = "http://localhost:45223/Service.svc";
        this.Url = pUrl;
    }

    /// <remarks/>
    public event GetTableCompletedEventHandler GetTableCompleted;

    /// <remarks/>
    public event InsertTableCompletedEventHandler InsertTableCompleted;

    /// <remarks/>
    public event EditTableCompletedEventHandler EditTableCompleted;

    /// <remarks/>
    public event GetDetailTableCompletedEventHandler GetDetailTableCompleted;

    /// <remarks/>
    public event GetDetailFieldTableCompletedEventHandler GetDetailFieldTableCompleted;

    /// <remarks/>
    public event InsertDetailTableCompletedEventHandler InsertDetailTableCompleted;

    /// <remarks/>
    public event EditDetailTableCompletedEventHandler EditDetailTableCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Table[] GetTable([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] System.Nullable<int> value)
    {
        object[] results = this.Invoke("GetTable", new object[] {
                    value});
        return ((Table[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetTable(System.Nullable<int> value, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetTable", new object[] {
                    value}, callback, asyncState);
    }

    /// <remarks/>
    public Table[] EndGetTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Table[])(results[0]));
    }

    /// <remarks/>
    public void GetTableAsync(System.Nullable<int> value)
    {
        this.GetTableAsync(value, null);
    }

    /// <remarks/>
    public void GetTableAsync(System.Nullable<int> value, object userState)
    {
        if ((this.GetTableOperationCompleted == null))
        {
            this.GetTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableOperationCompleted);
        }
        this.InvokeAsync("GetTable", new object[] {
                    value}, this.GetTableOperationCompleted, userState);
    }

    private void OnGetTableOperationCompleted(object arg)
    {
        if ((this.GetTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTableCompleted(this, new GetTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/InsertTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool InsertTable(Table table)
    {
        object[] results = this.Invoke("InsertTable", new object[] {
                    table});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginInsertTable(Table table, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("InsertTable", new object[] {
                    table}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndInsertTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void InsertTableAsync(Table table)
    {
        this.InsertTableAsync(table, null);
    }

    /// <remarks/>
    public void InsertTableAsync(Table table, object userState)
    {
        if ((this.InsertTableOperationCompleted == null))
        {
            this.InsertTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertTableOperationCompleted);
        }
        this.InvokeAsync("InsertTable", new object[] {
                    table}, this.InsertTableOperationCompleted, userState);
    }

    private void OnInsertTableOperationCompleted(object arg)
    {
        if ((this.InsertTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertTableCompleted(this, new InsertTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/EditTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool EditTable(Table table)
    {
        object[] results = this.Invoke("EditTable", new object[] {
                    table});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginEditTable(Table table, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("EditTable", new object[] {
                    table}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndEditTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void EditTableAsync(Table table)
    {
        this.EditTableAsync(table, null);
    }

    /// <remarks/>
    public void EditTableAsync(Table table, object userState)
    {
        if ((this.EditTableOperationCompleted == null))
        {
            this.EditTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditTableOperationCompleted);
        }
        this.InvokeAsync("EditTable", new object[] {
                    table}, this.EditTableOperationCompleted, userState);
    }

    private void OnEditTableOperationCompleted(object arg)
    {
        if ((this.EditTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EditTableCompleted(this, new EditTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetDetailTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public DetailTable[] GetDetailTable(int id)
    {
        object[] results = this.Invoke("GetDetailTable", new object[] {
                    id});
        return ((DetailTable[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetDetailTable(int id, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetDetailTable", new object[] {
                    id}, callback, asyncState);
    }

    /// <remarks/>
    public DetailTable[] EndGetDetailTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((DetailTable[])(results[0]));
    }

    /// <remarks/>
    public void GetDetailTableAsync(int id)
    {
        this.GetDetailTableAsync(id, null);
    }

    /// <remarks/>
    public void GetDetailTableAsync(int id, object userState)
    {
        if ((this.GetDetailTableOperationCompleted == null))
        {
            this.GetDetailTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailTableOperationCompleted);
        }
        this.InvokeAsync("GetDetailTable", new object[] {
                    id}, this.GetDetailTableOperationCompleted, userState);
    }

    private void OnGetDetailTableOperationCompleted(object arg)
    {
        if ((this.GetDetailTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDetailTableCompleted(this, new GetDetailTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetDetailFieldTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public DetailTable[] GetDetailFieldTable(int id)
    {
        object[] results = this.Invoke("GetDetailFieldTable", new object[] {
                    id});
        return ((DetailTable[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetDetailFieldTable(int id, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetDetailFieldTable", new object[] {
                    id}, callback, asyncState);
    }

    /// <remarks/>
    public DetailTable[] EndGetDetailFieldTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((DetailTable[])(results[0]));
    }

    /// <remarks/>
    public void GetDetailFieldTableAsync(int id)
    {
        this.GetDetailFieldTableAsync(id, null);
    }

    /// <remarks/>
    public void GetDetailFieldTableAsync(int id, object userState)
    {
        if ((this.GetDetailFieldTableOperationCompleted == null))
        {
            this.GetDetailFieldTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailFieldTableOperationCompleted);
        }
        this.InvokeAsync("GetDetailFieldTable", new object[] {
                    id}, this.GetDetailFieldTableOperationCompleted, userState);
    }

    private void OnGetDetailFieldTableOperationCompleted(object arg)
    {
        if ((this.GetDetailFieldTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDetailFieldTableCompleted(this, new GetDetailFieldTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/InsertDetailTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool InsertDetailTable(DetailTable table)
    {
        object[] results = this.Invoke("InsertDetailTable", new object[] {
                    table});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginInsertDetailTable(DetailTable table, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("InsertDetailTable", new object[] {
                    table}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndInsertDetailTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void InsertDetailTableAsync(DetailTable table)
    {
        this.InsertDetailTableAsync(table, null);
    }

    /// <remarks/>
    public void InsertDetailTableAsync(DetailTable table, object userState)
    {
        if ((this.InsertDetailTableOperationCompleted == null))
        {
            this.InsertDetailTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDetailTableOperationCompleted);
        }
        this.InvokeAsync("InsertDetailTable", new object[] {
                    table}, this.InsertDetailTableOperationCompleted, userState);
    }

    private void OnInsertDetailTableOperationCompleted(object arg)
    {
        if ((this.InsertDetailTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertDetailTableCompleted(this, new InsertDetailTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/EditDetailTable", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool EditDetailTable(DetailTable table)
    {
        object[] results = this.Invoke("EditDetailTable", new object[] {
                    table});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginEditDetailTable(DetailTable table, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("EditDetailTable", new object[] {
                    table}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndEditDetailTable(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void EditDetailTableAsync(DetailTable table)
    {
        this.EditDetailTableAsync(table, null);
    }

    /// <remarks/>
    public void EditDetailTableAsync(DetailTable table, object userState)
    {
        if ((this.EditDetailTableOperationCompleted == null))
        {
            this.EditDetailTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditDetailTableOperationCompleted);
        }
        this.InvokeAsync("EditDetailTable", new object[] {
                    table}, this.EditDetailTableOperationCompleted, userState);
    }

    private void OnEditDetailTableOperationCompleted(object arg)
    {
        if ((this.EditDetailTableCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EditDetailTableCompleted(this, new EditDetailTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class Table
{

    private int idField;

    private string codeField;

    private string descriptionField;

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class DetailTable
{

    private int idField;

    private int idTableField;

    private string tableField;

    private string fieldField;

    private string valueField;

    private string aux1Field;

    private string aux2Field;

    private string aux3Field;

    private string aux4Field;

    private string aux5Field;

    private string aux6Field;

    private string aux7Field;

    private string aux8Field;

    private string aux9Field;

    private string aux10Field;

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public int IdTable
    {
        get
        {
            return this.idTableField;
        }
        set
        {
            this.idTableField = value;
        }
    }

    /// <remarks/>
    public string Table
    {
        get
        {
            return this.tableField;
        }
        set
        {
            this.tableField = value;
        }
    }

    /// <remarks/>
    public string Field
    {
        get
        {
            return this.fieldField;
        }
        set
        {
            this.fieldField = value;
        }
    }

    /// <remarks/>
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    public string Aux1
    {
        get
        {
            return this.aux1Field;
        }
        set
        {
            this.aux1Field = value;
        }
    }

    /// <remarks/>
    public string Aux2
    {
        get
        {
            return this.aux2Field;
        }
        set
        {
            this.aux2Field = value;
        }
    }

    /// <remarks/>
    public string Aux3
    {
        get
        {
            return this.aux3Field;
        }
        set
        {
            this.aux3Field = value;
        }
    }

    /// <remarks/>
    public string Aux4
    {
        get
        {
            return this.aux4Field;
        }
        set
        {
            this.aux4Field = value;
        }
    }

    /// <remarks/>
    public string Aux5
    {
        get
        {
            return this.aux5Field;
        }
        set
        {
            this.aux5Field = value;
        }
    }

    /// <remarks/>
    public string Aux6
    {
        get
        {
            return this.aux6Field;
        }
        set
        {
            this.aux6Field = value;
        }
    }

    /// <remarks/>
    public string Aux7
    {
        get
        {
            return this.aux7Field;
        }
        set
        {
            this.aux7Field = value;
        }
    }

    /// <remarks/>
    public string Aux8
    {
        get
        {
            return this.aux8Field;
        }
        set
        {
            this.aux8Field = value;
        }
    }

    /// <remarks/>
    public string Aux9
    {
        get
        {
            return this.aux9Field;
        }
        set
        {
            this.aux9Field = value;
        }
    }

    /// <remarks/>
    public string Aux10
    {
        get
        {
            return this.aux10Field;
        }
        set
        {
            this.aux10Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetTableCompletedEventHandler(object sender, GetTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public Table[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((Table[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void InsertTableCompletedEventHandler(object sender, InsertTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal InsertTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EditTableCompletedEventHandler(object sender, EditTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EditTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal EditTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetDetailTableCompletedEventHandler(object sender, GetDetailTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDetailTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetDetailTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public DetailTable[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((DetailTable[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetDetailFieldTableCompletedEventHandler(object sender, GetDetailFieldTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDetailFieldTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetDetailFieldTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public DetailTable[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((DetailTable[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void InsertDetailTableCompletedEventHandler(object sender, InsertDetailTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertDetailTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal InsertDetailTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EditDetailTableCompletedEventHandler(object sender, EditDetailTableCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EditDetailTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal EditDetailTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
