//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TransactionManager
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CA25 : Transaction
	{
		public CA25()
		{
		}

		public override bool Validate()
		{
			throw new System.NotImplementedException();
		}

	}
}

